### ISSUE TITLE
Instances start problem

### ISSUE THREAD

**Issue by W0lfyZRex** [Skungee/ServerInstancesSkript#21]
So when i try to create an instance, the server indeed gets copied from the template but doesn't start.
It says in the console that it "started" in debug mode but it didnt, i don't have the logs folder or things like that and when i try to connect to it it just throws an annotatedconnectexeption right away.

What happens :
![image](https://user-images.githubusercontent.com/66094336/94973113-26e12300-050b-11eb-969f-7d6b68e05b76.png)

![image](https://user-images.githubusercontent.com/66094336/94973167-3eb8a700-050b-11eb-83ce-d059922a6a2b.png)

My serverinstances.yml config (without the tutorial part, i just scrolled down) :
![image](https://user-images.githubusercontent.com/66094336/94973205-52fca400-050b-11eb-9716-b5d282bfd2da.png)

My "test" template :
![image](https://user-images.githubusercontent.com/66094336/94973225-614ac000-050b-11eb-997d-207acc0539d1.png)

ServerInstances is enabled in the skungee config, i replicated everything as it said in the tutorial in the serverinstances.yml, i really don't know why it doesn't work.

**Comment by W0lfyZRex** [comment]
I’m really pissed of right now, I’ll try on a 1.8 server tomorrow but that’s spectacular that I can’t get it to work :(

**Comment by W0lfyZRex** [comment]
Nah, still can't make it work, just saw that it uses the proxy's ram so i increased that and it still doesnt work

**Comment by W0lfyZRex** [comment]
Weird but when i create an instance normally it doesnt start for whatever reason but when i specify the ram in the effect command it works BUT the server name is the name of the template, it completely ignores the server name i entered. And the weirdest thing is that it starts the server into the template directory instead of starting it in its own (i know that because i tried without the useless files like logs or permissions.yml etc and the files generated in my template and not in the temporary server directory.) also i never saw it delete a server folder or remove the server in the config.yml of the bungeecord so yea...

video : https://youtu.be/CLQ72iWWSwA

**Comment by CoreTechMC** [comment]
Hi, i have this problem too...

**Comment by TheLimeGlass** [comment]
Fixed in ServerInstances 2.0.0 which is going live when SkUnity finds out why I can't upload to SkUnity.
